# This file contains all settings related to bungeecord server.
#
# You have to configure it only if you are using bungee mode (eggwars arenas on multiple servers),
# otherwise you don't have to upload eggwars plugin to your bungeecord server.

# Socket server port
#
# It can be any free port (not being used by any other service),
# that your socket server used for communication between spigot servers and bungeecord will run on.
#
# Remember to change the port in every spigot server eggwars settings.yml file to the one set below.
socket-port: 3000