# Everything here requires a restart when edited

modules:
  slimeworldmanager: false
  advancedreplay: false
  mode: MULTI_ARENA # MULTI_ARENA, BUNGEE, LOBBY

game:
  respawn-protection: 5 # In seconds

gui:
  # Used for filling empty slots in GUIs
  # To set this in GUIs, set "material" to "FILLER"
  filler: GRAY_STAINED_GLASS_PANE
  quickbuy:
    material: RED_STAINED_GLASS_PANE
    name: "&cEmpty Slot!"
    lore:
      - "&7This is a Quick Buy slot!"
      - ""
      - "&eSneak Click any item in the shop to add it here!"